### ISSUE TITLE
Some roblox wiki articles no longer exist D:

### ISSUE THREAD

**Issue by Jjx003** [EgoMoose/ExampleDump#1]
Roblox started moving wiki sites and some of your articles have disappeared D:

Is there somewhere else you can upload them?

And I love these tutorials btw

**Comment by EgoMoose** [comment]
Thanks for the support and the concern!

I’m debating migrating everything I’ve written to Github as markdown files. I’m somewhat interested in updating or rewriting a lot of my old articles as they are of lower quality and lack consistency. This will be a long process (few weeks) and I will likely only upload once I’ve finished everything.

In the meantime worry not, I made backups of everything so nothing is lost!
